export const pizzaData = [
//   {
//     id: 0,
//     type: "Veggie Pizzas",
//     name: "Veggie Supreme",
//     desc: "A delightful mix of fresh vegetables on a classic pizza base.",
//     image: "/pizza-img/pizza1.png",
//     recommended: true,
//     startingPrice: 10,
//   },
  {
    id: 1,
    type: "Vegan Plant Based Pizzas Square",
    name: "DELIGHTED VEGGIE TOP",
    desc: "A vegan pizza topped with a variety of fresh vegetables and plant-based cheese.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Vegan%20Plant%20Based%20Pizzas%20Square/1%20PB%20DELIGHTED%20VEGGIE%20TOP.jpg",
    recommended: false,
    topPicks: true,
    startingPrice: 12,
  },
  {
    id: 2,
    type: "Vegan Plant Based Pizzas Square",
    name: "GARDEN VEGGIE TOP",
    desc: "A vibrant vegan pizza with a garden of fresh vegetables and a tangy tomato sauce.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Vegan%20Plant%20Based%20Pizzas%20Square/2%20PB%20GARDEN%20VEGGIE%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 11,
  },
  {
    id: 3,
    type: "Vegan Plant Based Pizzas Square",
    name: "INDIAN VEGGIE TOP",
    desc: "A spicy vegan pizza inspired by Indian flavors, featuring a mix of vegetables and aromatic spices.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Vegan%20Plant%20Based%20Pizzas%20Square/3%20PB%20INDIAN%20VEGGIE%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 13,
  },
  {
    id: 4,
    type: "Vegan Plant Based Pizzas Square",
    name: "BBQ CHICKEN TOP",
    desc: "A vegan twist on BBQ chicken pizza, featuring plant-based chicken and smoky BBQ sauce.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Vegan%20Plant%20Based%20Pizzas%20Square/4%20PB%20BBQ%20CHICKEN%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 14,
  },
  {
    id: 5,
    type: "Vegan Plant Based Pizzas Square",
    name: "INDIAN STYLE CHICKEN TOP",
    desc: "A flavorful vegan pizza with plant-based chicken, inspired by Indian cuisine.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Vegan%20Plant%20Based%20Pizzas%20Square/5%20PB%20INDIAN%20STYLE%20CHICKEN%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 15,
  },
  {
    id: 6,
    type: "Vegan Plant Based Pizzas Square",
    name: "SUPREME PIZZA TOP",
    desc: "A supreme vegan pizza loaded with a variety of plant-based toppings and a rich tomato sauce.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Vegan%20Plant%20Based%20Pizzas%20Square/6%20PB%20SUPREME%20PIZZA%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 16,
  },
  {
    id: 7,
    type: "Vegan Plant Based Pizzas Square",
    name: "PEPPERONI PIZZA TOP",
    desc: "A vegan pepperoni pizza with plant-based pepperoni slices and a zesty tomato sauce.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Vegan%20Plant%20Based%20Pizzas%20Square/7%20PB%20PEPPERONI%20PIZZA%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 12,
  },
  {
    id: 8,
    type: "Vegan Plant Based Pizzas Square",
    name: "GARLIC CHICKEN COMBINATION TOP",
    desc: "A savory vegan pizza with plant-based garlic chicken and a blend of spices on a tomato base.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Vegan%20Plant%20Based%20Pizzas%20Square/8%20PB%20GARLIC%20CHICKEN%20COMBINATION%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 14,
  },
  {
    id: 9,
    type: "Vegan Plant Based Pizzas Square",
    name: "CHICKEN XTREME FRONT",
    desc: "An extreme vegan pizza with plant-based chicken, loaded with spices and a rich tomato sauce.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Vegan%20Plant%20Based%20Pizzas%20Square/9%20PB%20CHICKEN%20XTREME%20%20FRONT.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 17,
  },
  {
    id: 10,
    type: "Vegan Plant Based Pizzas Square",
    name: "CHEESE PIZZA TOP",
    desc: "A classic cheese pizza with a rich tomato base and a blend of vegan cheeses.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Vegan%20Plant%20Based%20Pizzas%20Square/10%20PB%20CHEESE%20PIZZA%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 11,
  },
  {
    id: 11,
    type: "Traditional Pizza Square",
    name: "ALL MEAT PIZZA TOP",
    desc: "A hearty pizza topped with a variety of meats, including pepperoni, sausage, and ham.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/1%20ALL%20MEAT%20PIZZA%20TOP.jpg",
    recommended: false,
    topPicks: true,
    startingPrice: 18,
  },
  {
    id: 12,
    type: "Traditional Pizza Square",
    name: "SUPREME PIZZA TOP",
    desc: "A supreme pizza loaded with a variety of toppings, including vegetables, meats, and cheeses.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/2.%20SUPREME%20PIZZA%20TOP.jpg",
    recommended: true,
    topPicks: false,
    startingPrice: 16,
  },
  {
    id: 13,
    type: "Traditional Pizza Square",
    name: "CLASSIC HAWAIIAN PIZZA TOP",
    desc: "A classic Hawaiian pizza topped with ham, pineapple, and a blend of cheeses.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/3%20CLASSIC%20HAWAIIAN%20PIZZA%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 14,
  },
  {
    id: 14,
    type: "Traditional Pizza Square",
    name: "CLASSIC COMBINATION PIZZA TOP",
    desc: "A classic combination pizza with a mix of meats, vegetables, and cheeses on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/4%20CLASSIC%20COMBINATION%20PIZZA%20TOP.JPEG",
    recommended: false,
    topPicks: false,
    startingPrice: 15,
  },
  {
    id: 15,
    type: "Traditional Pizza Square",
    name: "CHICKEN COMBINATION TOP",
    desc: "A delicious chicken combination pizza topped with grilled chicken, vegetables, and a blend of cheeses.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/5%20GARLIC%205%20CHICKEN%20COMBINATION%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 16,
  },
  {
    id: 16,
    type: "Traditional Pizza Square",
    name: "BBQ CHICKEN TOP",
    desc: "A flavorful BBQ chicken pizza topped with smoky BBQ sauce, grilled chicken, and a blend of cheeses.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/6%20BBQ%20CHICKEN%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 17,
  },
  {
    id: 17,
    type: "Traditional Pizza Square",
    name: "CHICKEN BACON RANCH TOP",
    desc: "A savory chicken bacon ranch pizza topped with grilled chicken, crispy bacon, and ranch dressing.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/7%20CHICKEN%20BACON%20RANCH%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 18,
  },
  {
    id: 18,
    type: "Traditional Pizza Square",
    name: "BUFFALO RANCH CHICKEN PIZZA",
    desc: "A spicy buffalo ranch chicken pizza topped with buffalo sauce, grilled chicken, and a blend of cheeses.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/8%20BUFFALO%20RANCH%20CHICKEN%20PIZZA%20.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 16,
  },
  {
    id: 19,
    type: "Traditional Pizza Square",
    name: "CHICKEN XTREME FRONT",
    desc: "An extreme chicken pizza loaded with grilled chicken, extra cheese, and bold spices on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/9%20CHICKEN%20XTREME%20%20FRONT.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 17,
  },
  {
    id: 20,
    type: "Traditional Pizza Square",
    name: "MEDITERRANEAN PIZZA",
    desc: "A Mediterranean-inspired pizza featuring olives, feta cheese, sun-dried tomatoes, and herbs on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/10%20MEDITERRANEAN%20PIZZA%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 16,
  },
  {
    id: 21,
    type: "Traditional Pizza Square",
    name: "CANADIAN CLASSIC",
    desc: "A Canadian classic pizza topped with bacon, mushrooms, and a blend of cheeses on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/11%20CANADIAN%20CLASSIC%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 15,
  },
  {
    id: 22,
    type: "Traditional Pizza Square",
    name: "SABOR FIESTA",
    desc: "A festive pizza with Mexican-inspired flavors, featuring spicy toppings, jalapeños, and a zesty sauce.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/12%20SABOR%20FIESTA%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 16,
  },
  {
    id: 23,
    type: "Traditional Pizza Square",
    name: "LAMB KABOB PIZZA",
    desc: "A unique pizza topped with tender lamb kabob, fresh vegetables, and a tangy sauce on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/13%20LAMB%20KABOB%20PIZZA%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 19,
  },
  {
    id: 24,
    type: "Traditional Pizza Square",
    name: "CHEESE PIZZA",
    desc: "A classic cheese pizza with a rich tomato sauce and a generous blend of premium cheeses on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/14%20CHEESE%20PIZZA%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 12,
  },
  {
    id: 25,
    type: "Traditional Pizza Square",
    name: "PEPPERONI PIZZA",
    desc: "A timeless favorite featuring zesty pepperoni slices on a bed of melted cheese and tomato sauce.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/15%20PEPPERONI%20PIZZA%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 14,
  },
  {
    id: 26,
    type: "Traditional Pizza Square",
    name: "VEGGIE ADDICT",
    desc: "A vegetarian delight loaded with a variety of fresh vegetables, herbs, and a blend of cheeses on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/16%20VEGGIE%20ADDICT%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 15,
  },
  {
    id: 27,
    type: "Traditional Pizza Square",
    name: "MANGOLICIOUS PIZZA",
    desc: "A sweet and savory combination featuring fresh mango, specialty cheeses, and a hint of spice on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Traditional%20Pizza%20SQUARE/17%20MANGOLICIOUS%20PIZZA%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 17,
  },
  {
    id: 28,
    type: "Paneer Pizzas Square",
    name: "MALAI TIKKA PANEER POINT TOP",
    desc: "A rich and creamy paneer tikka pizza with a blend of Indian spices and fresh herbs on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Paneer Pizzas Square/1 MALAI TIKKA PANEER POINT TOP.jpg",
    recommended: false,
    topPicks: true,
    startingPrice: 16,
  },
  {
    id: 29,
    type: "Paneer Pizzas Square",
    name: "VEGGIE PANEER TOP",
    desc: "A vegetarian delight featuring cubes of paneer, fresh vegetables, and a savory sauce on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Paneer Pizzas Square/2 VEGGIE PANEER TOP.jpg",
    recommended: true,
    topPicks: false,
    startingPrice: 15,
  },
  {
    id: 30,
    type: "Paneer Pizzas Square",
    name: "WHITE SAUCE PANEER TOP",
    desc: "A creamy white sauce pizza topped with tender paneer cubes and a blend of herbs and spices.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Paneer Pizzas Square/3 WHITE SAUCE PANEER TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 16,
  },
  {
    id: 31,
    type: "Paneer Pizzas Square",
    name: "TIKKA PANEER TOP",
    desc: "A spicy tikka paneer pizza with marinated paneer chunks, bell peppers, and a tangy tikka sauce.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Paneer Pizzas Square/4 TIKKA PANEER TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 17,
  },
  {
    id: 32,
    type: "Paneer Pizzas Square",
    name: "TANDOORI PANEER TOP",
    desc: "A smoky tandoori paneer pizza with yogurt-marinated paneer, onions, and bell peppers on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Paneer Pizzas Square/5 TANDOORI PANEER TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 18,
  },
  {
    id: 33,
    type: "Paneer Pizzas Square",
    name: "CURRY MASALA PANEER TOP",
    desc: "An aromatic curry masala paneer pizza featuring paneer cubes in a rich curry sauce with Indian spices.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Paneer Pizzas Square/6 CURRY MASALA PANEER TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 17,
  },
  {
    id: 34,
    type: "Paneer Pizzas Square",
    name: "PANEER AACHARI TOP",
    desc: "A tangy paneer aachari pizza with pickle-spiced paneer, onions, and bell peppers on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Paneer Pizzas Square/7 PANEER AACHARI TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 16,
  },
  {
    id: 35,
    type: "Paneer Pizzas Square",
    name: "BUTTER PANEER TOP",
    desc: "A rich and indulgent butter paneer pizza with paneer cubes in a creamy butter sauce on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Paneer Pizzas Square/8 BUTTER PANEER TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 18,
  },
  {
    id: 36,
    type: "Paneer Pizzas Square",
    name: "PANEER PESTO TOP",
    desc: "A fusion paneer pesto pizza featuring paneer cubes, basil pesto sauce, and a blend of cheeses on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Paneer Pizzas Square/9 PANEER PESTO TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 17,
  },
  {
    id: 37,
    type: "Halal Pizzas Square",
    name: "HALAL MALAI TIKKA CHICKEN POINT TOP",
    desc: "A creamy halal pizza featuring tender malai tikka chicken pieces with traditional Indian spices.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Halal Pizzas Square 2/1 HALAL MALAI TIKKA CHICKEN POINT TOP.jpg",
    recommended: false,
    topPicks: true,
    startingPrice: 17,
  },
  {
    id: 38,
    type: "Halal Pizzas Square",
    name: "HALAL PESHAWRI STYLE CHICKEN TOP",
    desc: "A flavorful halal pizza with Peshawri-style chicken, aromatic spices, and fresh vegetables on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Halal Pizzas Square 2/2 HALAL PESHAWRI STYLE CHICKEN TOP.jpg",
    recommended: true,
    topPicks: false,
    startingPrice: 18,
  },
  {
    id: 39,
    type: "Halal Pizzas Square",
    name: "HALAL TIKKA CHICKEN TOP",
    desc: "A spicy halal tikka chicken pizza with marinated chicken pieces, bell peppers, and onions on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Halal%20Pizzas%20Square%202/3%20%20HALAL%20TIKKA%20CHICKEN%20TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 16,
  },
  {
    id: 40,
    type: "Halal Pizzas Square",
    name: "HALAL TANDOORI CHICKEN TOP",
    desc: "A smoky halal tandoori chicken pizza with yogurt-marinated chicken, onions, and bell peppers.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Halal Pizzas Square 2/4 HALAL TANDOORI CHICKEN TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 17,
  },
  {
    id: 41,
    type: "Halal Pizzas Square",
    name: "HALAL CURRY CHICKEN TOP",
    desc: "An aromatic halal curry chicken pizza featuring tender chicken pieces in a rich curry sauce with Indian spices.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Halal Pizzas Square 2/5 HALAL CURRY CHICKEN TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 18,
  },
  {
    id: 42,
    type: "Halal Pizzas Square",
    name: "HALAL CHICKEN AACHARI TOP",
    desc: "A tangy halal chicken aachari pizza with pickle-spiced chicken, onions, and bell peppers on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Halal Pizzas Square 2/6 HALAL CHICKEN AACHARI TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 17,
  },
  {
    id: 43,
    type: "Halal Pizzas Square",
    name: "HALAL CHICKEN PESTO TOP",
    desc: "A fusion halal chicken pesto pizza featuring tender chicken pieces, basil pesto sauce, and a blend of cheeses.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Halal Pizzas Square 2/7 HALAL CHICKEN PESTO TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 18,
  },
  {
    id: 44,
    type: "Halal Pizzas Square",
    name: "HALAL BUTTER CHICKEN TOP",
    desc: "A rich and indulgent halal butter chicken pizza with tender chicken in a creamy butter sauce on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Halal Pizzas Square 2/8 HALAL BUTTER CHICKEN TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 19,
  },
  {
    id: 45,
    type: "Halal Pizzas Square",
    name: "HALAL LAMB KABOB PIZZA TOP",
    desc: "A savory halal pizza topped with tender lamb kabob pieces, fresh vegetables, and a blend of spices.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Halal Pizzas Square 2/9 HALAL LAMB KABOB PIZZA TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 20,
  },
  {
    id: 46,
    type: "Halal Pizzas Square",
    name: "HALAL MEDITERRANEAN PIZZA TOP",
    desc: "A Mediterranean-inspired halal pizza featuring olives, feta cheese, halal meats, and a blend of aromatic herbs.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Halal Pizzas Square 2/10 HALAL MEDITERRANEAN PIZZA TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 17,
  },
  {
    id: 47,
    type: "Halal Pizzas Square",
    name: "HALAL PEPPERONI PIZZA TOP",
    desc: "A classic halal pepperoni pizza with zesty halal pepperoni slices on a bed of melted cheese and tomato sauce.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Halal Pizzas Square 2/11 HALAL PEPPERONI PIZZA TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 16,
  },
  {
    id: 48,
    type: "Chicken Pizzas Square",
    name: "MALAI TIKKA CHICKEN POINT TOP",
    desc: "A creamy chicken pizza featuring succulent malai tikka chicken pieces with aromatic spices and herbs.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Chicken Pizzas Square/1 MALAI TIKKA CHICKEN POINT TOP.jpg",
    recommended: false,
    topPicks: true,
    startingPrice: 17,
  },
  {
    id: 49,
    type: "Chicken Pizzas Square",
    name: "INDIAN STYLE CHICKEN TOP",
    desc: "A flavorful pizza with Indian-style chicken, featuring a blend of traditional spices on a classic crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Chicken Pizzas Square/2 INDIAN STYLE CHICKEN TOP.jpg",
    recommended: true,
    topPicks: false,
    startingPrice: 16,
  },
  {
    id: 50,
    type: "Chicken Pizzas Square",
    name: "TIKKA CHICKEN TOP",
    desc: "A spicy tikka chicken pizza with marinated chicken pieces, bell peppers, and a tangy tikka sauce.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Chicken%20Pizzas%20Square/3%20%20TIKKA%20CHICKEN%20TOP.jpg",
    recommended: false,
    topPicks: true,
    startingPrice: 17,
  },
  {
    id: 51,
    type: "Chicken Pizzas Square",
    name: "TANDOORI CHICKEN TOP",
    desc: "A smoky tandoori chicken pizza with yogurt-marinated chicken, onions, and bell peppers on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Chicken Pizzas Square/4 TANDOORI CHICKEN TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 18,
  },
  {
    id: 52,
    type: "Chicken Pizzas Square",
    name: "CURRY MASALA CHICKEN TOP",
    desc: "An aromatic curry masala chicken pizza featuring tender chicken pieces in a rich curry sauce with Indian spices.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Chicken Pizzas Square/5 CURRY MASALA CHICKEN TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 17,
  },
  {
    id: 53,
    type: "Chicken Pizzas Square",
    name: "CHICKEN ACHARI TOP",
    desc: "A tangy chicken achari pizza with pickle-spiced chicken, onions, and bell peppers on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Chicken Pizzas Square/6 CHICKEN ACHARI TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 16,
  },
  {
    id: 54,
    type: "Chicken Pizzas Square",
    name: "CHICKEN PESTO TOP",
    desc: "A flavorful chicken pesto pizza featuring tender chicken pieces, fresh basil pesto sauce, and a blend of cheeses.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Chicken Pizzas Square/7 CHICKEN PESTO TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 18,
  },
  {
    id: 55,
    type: "Chicken Pizzas Square",
    name: "BUTTER CHICKEN TOP",
    desc: "A rich and creamy butter chicken pizza with tender chicken pieces in a velvety butter sauce on a traditional crust.",
    image:
      "https://pub-af531d0497a24cdbb5d20c58edde5c58.r2.dev/pizza_point/Chicken Pizzas Square/8 BUTTER CHICKEN TOP.jpg",
    recommended: false,
    topPicks: false,
    startingPrice: 19,
  },
];
